### ISSUE TITLE
ingridt123's to-do list

### ISSUE THREAD

**Issue by ingridt123** [ingridt123/Snap-Note#2]
## To Do List

- [x] Create an issue
- [x] Create a branch
- [ ] Create file locally and push it
- [ ] Create a PR
- [ ] Edit files on GitHub and pull it
- [ ] Merge a PR
- [ ] Have a good time! 😄 

:shipit: 👍
